### ISSUE TITLE
Error: Cannot find module 'browser-sync'

### ISSUE THREAD

**Issue by baliomega** [fakhrullah/nasihati#16]
Saya dapat error ni bila run `gulp watch`

```
KL-PT-065:nasihati izwan$ gulp watch
module.js:472
    throw err;
    ^

Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/izwan/Documents/Baliomega/nasihati/gulpfile.js:1:81)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by fakhrullah** [comment]
Jap nak kena check dulu.

**Comment by fakhrullah** [comment]
Oh, sebab saya tak masukkan `browser-sync` dalam package.json.

**penyelesaian**

Install browser-sync tanpa --save flag. `npm install browser-sync`.
Kemudian, run `gulp watch`. Jadi kot.

**sebab masalah dan cadangan**

Saya install browser-sync secara global, `npm install browser-sync --global`, kemudian saya symlink bukan install `npm link browser-sync.
Sebabnya internet saya slow n nk jimat bandwith time tu.

Next, nak setup gulp + nodemon + express utk senangkan lagi hidup. Tapi tak terbuat lagi. Kalau ada masa try lah.

_:: github web, tak de desktop notificationkah?_

**Comment by baliomega** [comment]
Ok dah boleh `gulp watch`. Saya perlu `npm install` semua require plugin seperti yang tertera dalam `gulpfile.js`.

1. browser-sync
2. gulp-rename
3. gulp-contact
4. gulp-cssnano
5. postcss-cssnext
6. gulp-postcss
7. postcss-nested

*Setahu saya cuma ada notification dalam website github.com & email. Saya close yer issue ini. Thanks!

**Comment by fakhrullah** [comment]
Eh, banyaknya plugin tak masuk dalam package.json. Dh masuk todo list, nnt akan di fix. TQ, mmg x perasan dah psl ni.
